name: weather_insights
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  weather_icons: ^3.0.0
  lottie: ^2.6.0
  geolocator: ^10.1.0
  cupertino_icons: ^1.0.8
  geocoding: ^3.0.0
  flutter_native_splash: ^2.4.4
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1  # Latest version

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # Path to your logo file
  adaptive_icon_background: "#ffffff"  # Background color (for Android adaptive icons)
  adaptive_icon_foreground: "assets/logo.png"  # Foreground logo (optiona

flutter:
  uses-material-design: true  # ✅ Moved here
  assets:
    - assets/animations/sunny.json
    - assets/animations/cloudy.json
    - assets/animations/rain.json
    - assets/animations/thunderstorm.json
    - assets/animations/snow.json
    - assets/animations/smoke.json
    - assets/background.jpg
    - assets/logo.png

flutter_native_splash:
  image: assets/logo.png
  color: "#ffffff" # Change background color if needed
